# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/build-tools-ci:1.x
  working_directory: ~/example_drops_8_composer
  environment:
    #=========================================================================
    # In addition to the environment variables defined in this file, also
    # add the following variables in the Circle CI UI.
    #
    # See: https://circleci.com/docs/2.0/environment-variables/
    #
    # TERMINUS_SITE:  Name of the Pantheon site to run tests on, e.g. my_site
    # TERMINUS_TOKEN: The Pantheon machine token
    # GITHUB_TOKEN:   The GitHub personal access token
    # GIT_EMAIL:      The email address to use when making commits
    #
    # TEST_SITE_NAME: The name of the test site to provide when installing.
    # ADMIN_PASSWORD: The admin password to use when installing.
    # ADMIN_EMAIL:    The email address to give the admin when installing.
    #=========================================================================
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"

    # The variables below usually do not need to be modified.

    #======================================================================================================================================
    # Circle CI 2.0 does not yet expand environment variables so they have to be manually EXPORTed
    # Once environment variables can be expanded the variables below can be uncommented and the EXPORTs in set-up-globals.sh can be removed
    # See: https://discuss.circleci.com/t/unclear-how-to-work-with-user-variables-circleci-provided-env-variables/12810/11
    # See: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
    # See: https://discuss.circleci.com/t/circle-2-0-global-environment-variables/8681
    #======================================================================================================================================

    NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    ADMIN_USERNAME: admin
    BUILD_TOOLS_VERSION: dev-master
    TERM: dumb

version: 2
jobs:
    # @todo: common initialization: 'composer install' for the site-under-test
    build:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache
                    - terminus-install

            - run:
                # Set TERMINUS_ENV and related environment variables.
                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
                name: environment
                command: /build-tools-ci/scripts/set-environment

            - run:
                name: run composer install to get the vendor directory
                command: composer install

            - save_cache:
                key: composer-cache
                paths:
                    - $HOME/.composer/cache

            - save_cache:
                key: terminus-install
                paths:
                    - $(TERMINUS_PLUGINS_DIR:-~/.terminus/plugins)

            - run:
                name: lint php code for syntax errors
                command: composer -n lint

            - run:
                name: check coding standards
                command: composer -n code-sniff

            - run:
                name: run unit tests
                command: composer -n unit-test


    # config.yml file.
    lighthouse:
        docker:
            - image: quay.io/stevector/pantheon-ci-testing:master
        working_directory: ~/example_wordpress_composer
        steps:
            - checkout
            - run:
                name: dependencies
                # todo, get this file into something upstream.
                command: ./.circleci/set-up-global-vars.sh

            - run:
                name: install lighthouse-ci
                command: |
                  cd .circleci
                  git clone https://github.com/stevector/lighthouse-ci
                  cd lighthouse-ci/frontend
                  yarn install
                  cp no_pwa.js /tmp/artifacts/
            - run:
                name: lighthouse
                command: |
                  cd /tmp/artifacts
                  echo $PANTHEON_SITE_URL
                  echo $TERMINUS_ENV
                  lighthouse --chrome-flags="--headless --disable-gpu" "https://${TERMINUS_ENV}-${TERMINUS_SITE}.pantheonsite.io" --save-artifacts --save-assets --config-path=no_pwa.js --output=json --output=html
            - run:
                name: report results
                command: |
                  cd .circleci/lighthouse-ci/frontend
                  node pass_fail_pr.js --resultspath=$(find /tmp/artifacts/ -type f -name "*report.json" | head -n 1) --reporturl=${CIRCLE_ARTIFACTS_URL}/$(find /tmp/artifacts/ -type f -name "*report.html"  -exec basename {} \;  | head -n 1)
            - store_artifacts:
                path: /tmp/artifacts
                destination: artifacts


    build_deploy_and_test:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                keys:
                    - composer-cache
                    - terminus-install

            - run:
                # Set TERMINUS_ENV and related environment variables.
                # https://github.com/pantheon-systems/docker-build-tools-ci/blob/1.x/scripts/set-environment
                name: dependencies
                command: /build-tools-ci/scripts/set-environment

            - run:
                name: install dev dependencies, build assets, etc.
                command: ./.circleci/scripts/pantheon/01-prepare

            - run:
                name: build assets
                command: composer -n build-assets

            - run:
                name: prepare database for site-under test
                command: ./.circleci/scripts/pantheon/02-init-site-under-test-clone-existing
                # command: ./.circleci/scripts/pantheon/02-init-site-under-test-reinstall-new

            - run:
                name: run functional tests with Behat
                command: ./tests/scripts/run-behat

            - run:
                name: post-test actions
                command: ./.circleci/scripts/pantheon/03-post-test

            - run:
                name: handle merge to master (if needed)
                command: ./.circleci/scripts/pantheon/04-merge-master

            - run:
                name: remove transient test fixtures
                command: ./.circleci/scripts/pantheon/09-cleanup-fixtures

    # TODO:
    # 04-merge-master
    # 09-cleanup-fixtures

workflows:
  version: 2
  build_and_test:
    jobs:
      # Install dev dependencies and do simple tests (sniff, unit tests, etc.)
      - build
      # Build deploy and test on target platform
      - build_deploy_and_test
      - lighthouse:
          requires:
            - build_deploy_and_test
